service: certder-api-secure

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: us-central1
  project: certder
  credentials: ~/.gcloud/certder-albert.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  secure:
    handler: secure
    events:
      - http: secure